const translations = {
  en: {
    no_device: "Select a Freebox Server in the card editor.",
    no_entities: "No official Freebox entities were found for this device.",
    online: "Online",
    offline: "Unavailable",
    download: "Download",
    upload: "Upload",
    clients: "Clients",
    connected: "connected",
    wifi: "Wi-Fi",
    enabled: "Enabled",
    disabled: "Disabled",
    connection: "Connection",
    system: "System",
    storage: "Storage",
    equipment: "Freebox equipment",
    controls: "Controls",
    ipv4: "IPv4 address",
    ipv6: "IPv6 address",
    connection_type: "Access",
    system_uptime: "System uptime",
    connection_uptime: "Connection uptime",
    not_exposed: "Not exposed",
    firmware: "Firmware",
    hardware: "Hardware",
    serial: "Serial number",
    free_space: "free",
    missed_calls: "Missed calls",
    mark_calls_read: "Mark calls as read",
    reboot: "Reboot",
    hard_reboot: "Hard reboot",
    hard_reboot_running: "Power cycle in progress…",
    hard_reboot_failed: "Unable to start the Freebox hard reboot.",
    confirm_hard_reboot:
      "Power-cycle the Freebox now? Its power plug will be turned off for {seconds} seconds. Internet and local network access will be interrupted.",
    admin_required: "A Home Assistant administrator is required for this action.",
    web_ui: "Freebox OS",
    confirm_reboot:
      "Reboot the Freebox Server now? Internet and local network access will be interrupted.",
    confirm_wifi_off:
      "Turn Wi-Fi off? Wireless devices will immediately lose network access.",
    choose_device: "Freebox Server",
    title: "Title (optional)",
    view: "Layout",
    compact: "Compact",
    overview: "Overview",
    detailed: "Detailed",
    options: "Visible sections",
    show_connection: "Connection details",
    show_system: "Temperatures and fans",
    show_storage: "Storage and RAID",
    show_clients: "Connected clients",
    show_equipment: "Player, repeater, and phone",
    show_controls: "Controls",
    confirm_actions: "Confirm disruptive actions",
    max_clients: "Maximum displayed clients",
    hard_reboot_entity: "Freebox power plug (optional)",
    hard_reboot_delay: "Power-off duration in seconds",
    hard_reboot_help:
      "Select the Zigbee switch powering the Freebox. The full power cycle runs inside Home Assistant.",
    more_clients: "more clients",
    show_fewer_clients: "Show fewer clients",
    player: "Freebox Player",
    repeater: "Wi-Fi repeater",
    phone: "Phone",
    active: "Active",
    inactive: "Inactive",
    unavailable: "Unavailable",
    temperatures: "Temperatures",
    fans: "Fans",
    healthy: "Healthy",
    problem: "Problem",
    unknown: "Unknown",
    day: "d",
    hour: "h",
    minute: "min",
  },
  fr: {
    no_device: "Sélectionnez un Server Freebox dans l’éditeur de la carte.",
    no_entities:
      "Aucune entité de l’intégration officielle Freebox n’a été trouvée pour cet appareil.",
    online: "En ligne",
    offline: "Indisponible",
    download: "Descendant",
    upload: "Montant",
    clients: "Clients",
    connected: "connectés",
    wifi: "Wi-Fi",
    enabled: "Activé",
    disabled: "Désactivé",
    connection: "Connexion",
    system: "Système",
    storage: "Stockage",
    equipment: "Équipements Freebox",
    controls: "Contrôles",
    ipv4: "Adresse IPv4",
    ipv6: "Adresse IPv6",
    connection_type: "Accès",
    system_uptime: "Uptime système",
    connection_uptime: "Uptime connexion",
    not_exposed: "Non exposé",
    firmware: "Micrologiciel",
    hardware: "Matériel",
    serial: "Numéro de série",
    free_space: "libres",
    missed_calls: "Appels manqués",
    mark_calls_read: "Marquer les appels comme lus",
    reboot: "Redémarrer",
    hard_reboot: "Hard reboot",
    hard_reboot_running: "Coupure électrique en cours…",
    hard_reboot_failed: "Impossible de lancer le hard reboot de la Freebox.",
    confirm_hard_reboot:
      "Effectuer un hard reboot de la Freebox ? Sa prise sera coupée pendant {seconds} secondes. Internet et le réseau local seront interrompus.",
    admin_required: "Cette action nécessite un compte administrateur Home Assistant.",
    web_ui: "Freebox OS",
    confirm_reboot:
      "Redémarrer le Server Freebox maintenant ? Internet et le réseau local seront interrompus.",
    confirm_wifi_off:
      "Désactiver le Wi-Fi ? Les appareils sans fil perdront immédiatement leur accès réseau.",
    choose_device: "Server Freebox",
    title: "Titre (facultatif)",
    view: "Disposition",
    compact: "Compacte",
    overview: "Vue d’ensemble",
    detailed: "Détaillée",
    options: "Sections visibles",
    show_connection: "Détails de connexion",
    show_system: "Températures et ventilateurs",
    show_storage: "Stockage et RAID",
    show_clients: "Clients connectés",
    show_equipment: "Player, répéteur et téléphone",
    show_controls: "Contrôles",
    confirm_actions: "Confirmer les actions perturbatrices",
    max_clients: "Nombre maximal de clients affichés",
    hard_reboot_entity: "Prise électrique de la Freebox (facultatif)",
    hard_reboot_delay: "Durée de la coupure en secondes",
    hard_reboot_help:
      "Sélectionnez la prise Zigbee qui alimente la Freebox. Le cycle complet est exécuté dans Home Assistant.",
    more_clients: "clients supplémentaires",
    show_fewer_clients: "Afficher moins de clients",
    player: "Freebox Player",
    repeater: "Répéteur Wi-Fi",
    phone: "Téléphone",
    active: "Actif",
    inactive: "Inactif",
    unavailable: "Indisponible",
    temperatures: "Températures",
    fans: "Ventilateurs",
    healthy: "Sain",
    problem: "Problème",
    unknown: "Inconnu",
    day: "j",
    hour: "h",
    minute: "min",
  },
};

export function localize(language, key) {
  const locale = String(language || "en").split("-")[0];
  return translations[locale]?.[key] || translations.en[key] || key;
}
